apiVersion: 1

datasources:
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    isDefault: true
    jsonData:
      maxLines: 5000
      timeout: 60
    version: 1
    editable: false
